Repository KellyQiuu/195Final, pull requests merged in 2023-11, with the labels that each got.

#1 10.30 Ziyi
  src/data_access/UserDataAccessObject.java
  src/entity/User.java
  src/use_case/SignupUserAccessInterface.java
Labels: help wanted

#2 modified file structure into sub_packages, added some profile views.
  src/app/UserListUseCaseFactory.java
  src/entity/UserFactory.java
  src/interface_adapter/UserListState.java
  src/interface_adapter/UserListViewModel.java
  src/interface_adapter/ViewManagerModel.java
  src/interface_adapter/ViewModel.java
  src/interface_adapter/profile/ProfileViewModel.java
  src/interface_adapter/user_list/UserListController.java
  src/interface_adapter/user_list/UserListPresenter.java
  src/interface_adapter/user_list/UserListState.java
  src/interface_adapter/user_list/UserListViewModel.java
  src/use_case/user_list/UserListDataAccessInterface.java
  src/use_case/user_list/UserListInputBoundary.java
  src/use_case/user_list/UserListInputData.java
  src/use_case/user_list/UserListInteractor.java
  src/use_case/user_list/UserListOutputBoundary.java
  src/use_case/user_list/UserListOutputData.java
  src/view/ProfileView.java
  src/view/ViewManager.java
Labels: enhancement

#4 modified profileview and viewmanager
  src/view/ProfileView.java
  src/view/ViewManager.java
Labels: question

#5 Added interface adapter and use case for signup
  src/data_access/UserDataAccessObject.java
  src/interface_adapter/signup/SignupController.java
  src/interface_adapter/signup/SignupPresenter.java
  src/use_case/signup/SignupInputBoundary.java
  src/use_case/signup/SignupInputData.java
  src/use_case/signup/SignupInteractor.java
  src/use_case/signup/SignupOutputBoundary.java
  src/use_case/signup/SignupOutputData.java
  src/use_case/signup/SignupUserAccessInterface.java
Labels: enhancement

#8 added profile interface adaptor and profile use case
  .gitignore
  src/data_access/UserDataAccessObject.java
  src/interface_adapter/profile/ProfileController.java
  src/interface_adapter/profile/ProfilePresenter.java
  src/use_case/profile/ProfileDataAccessInterface.java
  src/use_case/profile/ProfileInputBoundary.java
  src/use_case/profile/ProfileInputData.java
  src/use_case/profile/ProfileInteractor.java
  src/use_case/profile/ProfileOutputBoundary.java
  src/use_case/profile/ProfileOutputData.java
Labels: enhancement
